### ISSUE TITLE
Support for Pass/Fail in grading

### ISSUE THREAD

**Issue by madsobitsoe** [kfl/staffeli_nt#11]
The grading scheme in PoP differs from the grading scheme in AP/PCS. 

We give points per subtask and if more than half the points are obtained the assignment is passed. 
The actual grade posted on absalon is either 0 (Fail) or passed (1) - regardless of the amount of points. 

I think this could be easily implemented in the GradingSheet class, either by a flag (quick fix) or by subclassing it. 
--passfail could be an argument to upload.py that will or maybe we could add a(n optional) field to the template.yaml files.

**Comment by kfl** [comment]
I think I like the solution of adding a field to the template best.

**Comment by kfl** [comment]
I'm think a good solution is to add an optional integer field `passing-ponts` to templates.

Thus, a (minimal) template could look like:

```yaml
name: Mini asignment
parsing-points: 3

tasks:
  - overall:
      title: Overall
      points: 6
      rubric: |
        Your code and report are unreadable
```

Adding this field will have the effect, that the grade posted to Absalon is `1` if the total sum of points is greater than or equal to `parsing-points`, and `0` otherwise.

If the field is not added, the behaviour is unchanged.

@madsobitsoe does that sound reasonable?
